<%

let meta = {
	creates: {
		fileName: "docker-containers/elixir/Dockerfile"
	},
	depends_on: []
} 

%>FROM erlang:21-alpine

# elixir expects utf8.
ENV ELIXIR_VERSION="v1.8.1" \
	LANG=C.UTF-8 \
    SCAFFOLD_APP_NAME=phoenix_app \
    DATABASE_USER=postgres \
    DATABASE_PASSWORD=postgres \
    DATABASE_NAME=postgres \
    DATABASE_TEST_NAME=postgres_test \
    DATABASE_HOST=db \
    DATABASE_PORT=5432

RUN set -xe \
	&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/archive/${ELIXIR_VERSION}.tar.gz" \
	&& ELIXIR_DOWNLOAD_SHA256="de8c636ea999392496ccd9a204ccccbc8cb7f417d948fd12692cda2bd02d9822" \
	&& buildDeps=' \
		ca-certificates \
		curl \
		make \
	' \
	&& apk add --no-cache --virtual .build-deps $buildDeps \
    && apk add --no-cache inotify-tools \
	&& curl -fSL -o elixir-src.tar.gz $ELIXIR_DOWNLOAD_URL \
	&& echo "$ELIXIR_DOWNLOAD_SHA256  elixir-src.tar.gz" | sha256sum -c - \
	&& mkdir -p /usr/local/src/elixir \
	&& tar -xzC /usr/local/src/elixir --strip-components=1 -f elixir-src.tar.gz \
	&& rm elixir-src.tar.gz \
	&& cd /usr/local/src/elixir \
	&& make install clean \
	&& apk del .build-deps

RUN mix local.hex --force \
    && mix local.rebar --force

RUN mix archive.install --force hex phx_new 1.4.0

WORKDIR /app
ADD . /app
#CMD ["ls", "/"]
ENTRYPOINT ["/scripts/docker-entrypoint.sh"]
CMD ["server"]